### ISSUE TITLE
Logo For Score Board

### ISSUE THREAD

**Issue by zularizal** [superbderrick/ScoreBoard#1]
Hello @superbderrick , I am a graphic designer, I want to help others in graphic design.

After I review your project, you have no logo on this project yet. Therefore I want to contribute to this project by creating a new logo / icons. It's free for your project. What do you think?

**Comment by superbderrick** [comment]
Hi , @zularizal  it sounds great 👍 , go head
now this app is not perfect version, it can add feature to change whole app theme,, 

anyway let me know after review my app and your opinions

**Comment by zularizal** [comment]
Hi, I've made two logos, what do you think? which one do you like? if anything i want to change please let me know.

And in my opinion, your application is good, maybe you need to add some more features.

![logo](https://user-images.githubusercontent.com/38547278/42208101-8f965276-7ed5-11e8-9958-768148bcf3ef.png)

**Comment by zularizal** [comment]
Hi, I already uploaded the logo to drive, you can see it in this link

https://drive.google.com/open?id=1gIi0aVZXjcd9LM7sDvBU6XZY5VjD6NOv


and also I have sent a pull request for you, please check #2 

Oh yes I have a little advice, can you later use the color of the material on the theme, I think it fits and matches this new logo.

**Comment by zularizal** [comment]
Okay...

One more thing, you should delete ic_launcher_round.png in the mipmap folder or you can replace it with the new icon.
